kind: Service
apiVersion: v1
metadata:
  name: dapr-localforwarder
  labels:
    app: dapr-localforwarder
spec:
  selector:
    app: dapr-localforwarder
  ports:
  - protocol: TCP
    port: 6789
    targetPort: 6789
  type: ClusterIP

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dapr-localforwarder
  labels:
    app: dapr-localforwarder
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dapr-localforwarder
  template:
    metadata:
      labels:
        app: dapr-localforwarder
    spec:
      containers:
      - name: dapr-localforwarder
        image: docker.io/daprio/dapr-localforwarder:0.1-beta1
        ports:
        - containerPort: 6789
        imagePullPolicy: Always
        env:
          - name: APPINSIGHTS_INSTRUMENTATIONKEY
            value: "<APPINSIGHT INSTRUMENTATIONKEY>"
          - name: APPINSIGHTS_LIVEMETRICSSTREAMAUTHENTICATIONAPIKEY
            value: "<APPINSIGHT API KEY>"
